### PR TITLE
77 deployment scripts

### LINKED ISSUE #77: DEVOPS: Streamline deployment scripts
**DUE DATE: 02/24/2019**

## SPECIFICATIONS
**As a** developer **I want to** deploy all the applications both locally and to the cloud **so that** we can accelerate testing and deployment.

### Acceptance Criteria
-   [x] All deployment scripts are idempotent
-   [x] Each script individually attempts to setup the network.
-   [x] The applications are built in the environment and deployed to Docker (i.e., not built in the container)
-   [x] Create a development environment setup for Ubuntu

#### Analysis
Idempotent scripts should run n times and produce the same result, that is, not aggregate or modify the state. Each script should attempt to setup the user-bridge network on Docker, unless the network exists, then it should just use it. Similarly, each script, in its default behavior, will check if the container already is running and let it be if so. Flags to override this behaviors can be passed to the scripts.

#### `docker-deploy-container.sh` ####
``` text
USAGE:
docker-deploy-container.sh CONTAINER DOCKERDIR LOCALPORT CONTAINERPORT [RECREATE]
     CONTAINER              container name (required argument)
     DOCKERDIR              Dockerfile directory path (relative to repo's root)
     LOCALPORT              port used to access from outside
     CONTAINERPORT          application's port outside container
     RECREATE               "yes" if you wish to force recreate the container (optional)
```
The script checks if the network is up, otherwise, it creates it by calling the `docker-setup-network.sh` script. After building the container, if another container with the same name is running, then it decides based on the RECREATE argument of the script, whether to remove the current one and replace it, or just end. The container's output is logged to a file under `/logs`.

#### `common-functions.sh` ####
A self explanatory file that contains batch functions that can be used by all scripts. This includes determining if a network setup is up, if a container is running, finding the repo's root, logger, etc.

#### `docker-clean.sh` ####
Runs a system pruning on Docker. If passed a first argument "yes" it stops and removes all containers and images (nuclear option).

#### `docker-setup-network.sh` ####
Takes in a required argument and two optional arguments. The first argument indicates the network identifier. The second is set to "yes" if the caller desires to recreate a network that already exists. The third argument will take the action further by disconnecting all currently connected containers from the network, removing it, and recreating it.

#### `docker-deploy-mysql.sh` ####
Runs `docker-deploy-container.sh` with parameters
``` bash
CONTAINER="mysqldb"
DOCKERDIR="sql"
LOCALPORT="3306"
CONTAINERPORT="3306"
```
#### `docker-deploy-data-engine.sh` ####
Runs `docker-deploy-container.sh` with parameters
``` bash
CONTAINER="dataengine"
DOCKERDIR="dotnet/DataEngine"
LOCALPORT="6000"
CONTAINERPORT="7000"
```
#### `docker-deploy-template-engine.sh` ####
Runs `docker-deploy-container.sh` with parameters
``` bash
CONTAINER="templateengine"
DOCKERDIR="dotnet/TemplateEngine"
LOCALPORT="5000"
CONTAINERPORT="80"
```
#### `docker-deploy-all.sh` ####
Deploys everything in one run. Takes a MODE argument that expects
- "normal", doest not attempt to recreate the containers if existing
- "recreate", will attempt to recreate
- "nuclear", will clean and remove every container, image, network, etc

#### `build-n-publish-dotnet.sh` ####
Takes the path to a project, removes old builds under `./old/**` and republishes the project.
Used by `docker-deploy-data-engine.sh` and `docker-deploy-template-engine.sh` in the step previous to deploying.

---

## TESTS
|Given|When|Then|
|---|---|---|
|No network with id `networkid`|The `docker-setup-network.sh networkid` command is run|The network is created successfully|
|A network with id `networkid` and no containers connected to it|The `docker-setup-network.sh networkid` command is run|The script fails, reporting that a network with that name is already configured|
|A network with id "networkid" and no containers connected to it|The `docker-setup-network.sh networkid yes` command is run|The script recreates the network|
|A network with id "networkid" and at least one container connected to it|The `docker-setup-network.sh networkid yes` command is run|The script fails|
|A network with id "networkid" and at least one container connected to it|The `docker-setup-network.sh networkid yes yes` command is run|The script disconnects the containers and recreates the network|
|No `mysqldb` container and no network `simoorgnetwork`|The `docker-deploy-mysql.sh` script is executed|The script calls in a network setup, builds, and runs the container|
|No `mysqldb` container, but network `simoorgnetwork` is up|The `docker-deploy-mysql.sh` script is executed|The script uses the current network, builds, and runs the container|
|A `mysqldb` container running and network `simoorgnetwork` is up|The `docker-deploy-mysql.sh` script is executed|The script warns that the container already exists and exits|
|A `mysqldb` container running and network `simoorgnetwork` is up|The `docker-deploy-mysql.sh yes` script is executed (note the argument)|The script warns that the container already exists, stops it, removes it, builds the new one, runs it, and exits|

**The same tests were run for each deployment**

### PR DESCRIPTION
**Pull request by dacabdi**
gh-77
closes #77

### CODE REVIEW

**Comment by dacabdi** [comment]
@souljorn fixed all the issues with codefactor and codacy... can you review, and give it approval? Consider running the branch locally for reassurance. If so, I can close this today.

**Comment by souljorn** [comment]
The grep commands you use in common functions are failing due to the differences in Linux(GNU) and OSX(BSD) reference my posts on slack.

**Comment by dacabdi** [comment]
@technocharpie I just hit a roadblock on this PR, I am waiting for your input on the Go deployment.

**Comment by dacabdi** [comment]
> The grep commands you use in common functions are failing due to the differences in Linux(GNU) and OSX(BSD) reference my posts on slack.

Solved

**Comment by dacabdi** [comment]
@souljorn Deploying the DataEngine but building locally and then shipping to the container is done. Tested it with postman after manually doing a query to upload tags. I have to make it work in the pipeline now.

**Comment by technocharpie** [comment]
@dacabdi do you still have the roadblock with Go? or did you manage to fix it?

**Comment by souljorn** [comment]
Got an error on "recreate" mode when it builds the network.

**Comment by dacabdi** [comment]
> @dacabdi Got an error on "recreate" mode when it builds the network.
> Reference the image on slack . Other modes work fine.

With the current version of this branch?

**Comment by dacabdi** [comment]
> @dacabdi do you still have the roadblock with Go? or did you manage to fix it?

Still having issues with that. I don't know how to fix it.

**Pull request merged**
